### ISSUE TITLE
Update Violation table to have column violation_type and create queries for inserting the following records

### ISSUE THREAD

**Issue by karkiriks** [nikitkarki/RTVMS#22]
violation_type |           violationCharge |           violationDescription
  | RoadSigns |                     500                       | Failure to follow traffic lights
  | RoadSigns |                     500                     | Failure to follow road lane laws
  | RoadSigns |                     500                           | Failure to follow No Entry and/or One Way sign
  | RoadSigns |                     500                           | Failure to follow Road Lines Marking
  | Vehicle |                           1000                           | Vehicle Body Illegally Modified
  | Vehicle |                          1000                           | Passengers more than legally permitted
  | Vehicle |                          500                           | Violated Motorcycle Helmet policy
  | Vehicle |                           500                           | Vehicle Lights Illegally Modified/ Not in function
  | Vehicle |                           500                           | Vehicle Number Plates not clear
  | Vehicle |                           500                           | Vehicle Bluebook not carried
  | Vehicle |                           1500                           | Public Vehicle not stopping at bus-stop for passengers
  | Vehicle |                           1500                           | Operating Vehicle physically not safe in condition
  | Driver |                           1000                           | Operating Vehicle without a Licence
  | Driver |                           1000                           | Operating Vehicle without a Valid Licence
  | Driver |                           5000                           | Operating Vehicle under influence of alcohol
  | Driver |                           2000                           | Operating Vehicle in a reckless manner
  | Driver |                           1000                           | Overspeeding than the posted Speed Limit
  | Driver                           | 1000                           | Valid bluebook not in possesion of driver

**Comment by nikitkarki** [comment]
done
